//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace FazlaMesaiSureciYK.Entities {
    
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_OdemeTalepArsivi")]
    public class E_FazlaMesaiSureciYK_OdemeTalepArsiviEntity : FormEntity<E_FazlaMesaiSureciYK_OdemeTalepArsiviEntity> {
        
        private E_FazlaMesaiSureciYK_OdemeTalepArsiviVREntity _VersionEntity;
        
        private RDEntityCollection<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDMLEntity> _RD;
        
        private RDCEntityCollection<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCMLEntity> _RDC;
        
        public E_FazlaMesaiSureciYK_OdemeTalepArsiviEntity() {
            this.VersionEntity = new E_FazlaMesaiSureciYK_OdemeTalepArsiviVREntity();
            this.RD = new RDEntityCollection<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCMLEntity>();
        }
        
        public E_FazlaMesaiSureciYK_OdemeTalepArsiviVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_OdemeTalepArsiviVR")]
    public class E_FazlaMesaiSureciYK_OdemeTalepArsiviVREntity : VersionEntity<E_FazlaMesaiSureciYK_OdemeTalepArsiviVREntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_OdemeTalepArsiviRDC")]
    public class E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCEntity : RDCEntity<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCML")]
    public class E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCMLEntity : RDCMLEntity<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_OdemeTalepArsiviRD")]
    public class E_FazlaMesaiSureciYK_OdemeTalepArsiviRDEntity : RDEntity<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDEntity, E_FazlaMesaiSureciYK_OdemeTalepArsiviRDMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_OdemeTalepArsiviRDML")]
    public class E_FazlaMesaiSureciYK_OdemeTalepArsiviRDMLEntity : RDMLEntity<E_FazlaMesaiSureciYK_OdemeTalepArsiviRDMLEntity> {
    }
}




