//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace FazlaMesaiSureciYK.Entities {
    
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuEntity : FormEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _nbToplamFazlaMesai;
        
        private Bimser.Framework.Domain.DataField<decimal> _nbToplamMesaiUcret;
        
        private Bimser.Framework.Domain.DataField<string> _umTalepEden;
        
        private E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuVREntity _VersionEntity;
        
        private RDEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDMLEntity> _RD;
        
        private RDCEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuMLEntity> _ML;
        
        private GridEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiMLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity> _E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi;
        
        public E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuEntity() {
            this.ML = new MLEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuMLEntity>();
            this.VersionEntity = new E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuVREntity();
            this.RD = new RDEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCMLEntity>();
            this.E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi = new GridEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiMLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity>();
            this.E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi.MLEntityEnabled = true;
            this.E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi.SLEntityEnabled = false;
        }
        
        [ColumnOptionsAttribute(Name="nbToplamFazlaMesai", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> nbToplamFazlaMesai {
            get {
                return this._nbToplamFazlaMesai;
            }
            set {
                this._nbToplamFazlaMesai = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="nbToplamMesaiUcret", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> nbToplamMesaiUcret {
            get {
                return this._nbToplamMesaiUcret;
            }
            set {
                this._nbToplamMesaiUcret = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="umTalepEden", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> umTalepEden {
            get {
                return this._umTalepEden;
            }
            set {
                this._umTalepEden = value;
            }
        }
        
        public E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public GridEntityCollection<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiMLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity> E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi {
            get {
                return this._E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi;
            }
            set {
                this._E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi = value;
            }
        }
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuML")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuMLEntity : MLEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _umDepartman;
        
        [ColumnOptionsAttribute(Name="umDepartman", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> umDepartman {
            get {
                return this._umDepartman;
            }
            set {
                this._umDepartman = value;
            }
        }
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgi")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiEntity : GridEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiMLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtTarih;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _tpBaslangicSaati;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _tpBitisSaati;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _ProcessId;
        
        public E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiEntity() {
        }
        
        [ColumnOptionsAttribute(Name="dtTarih", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtTarih {
            get {
                return this._dtTarih;
            }
            set {
                this._dtTarih = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tpBaslangicSaati", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> tpBaslangicSaati {
            get {
                return this._tpBaslangicSaati;
            }
            set {
                this._tpBaslangicSaati = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tpBitisSaati", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> tpBitisSaati {
            get {
                return this._tpBitisSaati;
            }
            set {
                this._tpBitisSaati = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="ProcessId", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> ProcessId {
            get {
                return this._ProcessId;
            }
            set {
                this._ProcessId = value;
            }
        }
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiML")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiMLEntity : GridMLEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _umTalepEden;
        
        private Bimser.Framework.Domain.DataField<string> _umDepartman;
        
        private Bimser.Framework.Domain.DataField<string> _umUnvan;
        
        private Bimser.Framework.Domain.DataField<string> _nbFazlaMesaiSuresi;
        
        [ColumnOptionsAttribute(Name="umTalepEden", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> umTalepEden {
            get {
                return this._umTalepEden;
            }
            set {
                this._umTalepEden = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="umDepartman", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> umDepartman {
            get {
                return this._umDepartman;
            }
            set {
                this._umDepartman = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="umUnvan", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> umUnvan {
            get {
                return this._umUnvan;
            }
            set {
                this._umUnvan = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="nbFazlaMesaiSuresi", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> nbFazlaMesaiSuresi {
            get {
                return this._nbFazlaMesaiSuresi;
            }
            set {
                this._nbFazlaMesaiSuresi = value;
            }
        }
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSL")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLEntity : GridSLEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLML")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity : GridSLMLEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormu_dgMesaiBilgiSLMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuVR")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuVREntity : VersionEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuVREntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDC")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCEntity : RDCEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCML")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCMLEntity : RDCMLEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRD")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDEntity : RDEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDEntity, E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDMLEntity> {
    }
    
    [TableOptions(TableName="E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDML")]
    public class E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDMLEntity : RDMLEntity<E_FazlaMesaiSureciYK_FazlaMesaiOdemeFormuRDMLEntity> {
    }
}




