//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace EgitimTalepDegerlendirmeSureci.Entities {
    
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuEntity : FormEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuEntity> {
        
        private E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuVREntity _VersionEntity;
        
        private RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDMLEntity> _RD;
        
        private RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCMLEntity> _RDC;
        
        private GridEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity> _E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari;
        
        public E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuEntity() {
            this.VersionEntity = new E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuVREntity();
            this.RD = new RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCMLEntity>();
            this.E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari = new GridEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity>();
            this.E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari.MLEntityEnabled = true;
            this.E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari.SLEntityEnabled = false;
        }
        
        public E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public GridEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity> E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari {
            get {
                return this._E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari;
            }
            set {
                this._E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclari")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariEntity : GridEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _DGID;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtEgitimBasTarih;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtEgitimBitTarih;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _nbxOrtDegerlendirmePuan;
        
        public E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariEntity() {
        }
        
        [ColumnOptionsAttribute(Name="DGID", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> DGID {
            get {
                return this._DGID;
            }
            set {
                this._DGID = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="dtEgitimBasTarih", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtEgitimBasTarih {
            get {
                return this._dtEgitimBasTarih;
            }
            set {
                this._dtEgitimBasTarih = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="dtEgitimBitTarih", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtEgitimBitTarih {
            get {
                return this._dtEgitimBitTarih;
            }
            set {
                this._dtEgitimBitTarih = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="nbxOrtDegerlendirmePuan", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> nbxOrtDegerlendirmePuan {
            get {
                return this._nbxOrtDegerlendirmePuan;
            }
            set {
                this._nbxOrtDegerlendirmePuan = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariMLEntity : GridMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitimAdi;
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitmen;
        
        [ColumnOptionsAttribute(Name="tbxEgitimAdi", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitimAdi {
            get {
                return this._tbxEgitimAdi;
            }
            set {
                this._tbxEgitimAdi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tbxEgitmen", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitmen {
            get {
                return this._tbxEgitmen;
            }
            set {
                this._tbxEgitmen = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSL")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLEntity : GridSLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLML" +
        "")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity : GridSLMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporu_dgEgitimAnketSonuclariSLMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuVR")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuVREntity : VersionEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuVREntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDC")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCEntity : RDCEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCMLEntity : RDCMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRD")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDEntity : RDEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDMLEntity : RDMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimAnketRaporuRDMLEntity> {
    }
}




