//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace EgitimTalepDegerlendirmeSureci.Entities {
    
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnket")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketEntity : FormEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketEntity> {
        
        private Bimser.Framework.Domain.DataField<decimal> _nbxDegerlendirmepuan;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtEgitimBitTarihAnket;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtEgitimBasTarihAnket;
        
        private E_EgitimTalepDegerlendirmeSureci_FormAnketVREntity _VersionEntity;
        
        private RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketRDEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDMLEntity> _RD;
        
        private RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketMLEntity> _ML;
        
        public E_EgitimTalepDegerlendirmeSureci_FormAnketEntity() {
            this.ML = new MLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketMLEntity>();
            this.VersionEntity = new E_EgitimTalepDegerlendirmeSureci_FormAnketVREntity();
            this.RD = new RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketRDEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDCMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="nbxDegerlendirmepuan", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> nbxDegerlendirmepuan {
            get {
                return this._nbxDegerlendirmepuan;
            }
            set {
                this._nbxDegerlendirmepuan = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="dtEgitimBitTarihAnket", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtEgitimBitTarihAnket {
            get {
                return this._dtEgitimBitTarihAnket;
            }
            set {
                this._dtEgitimBitTarihAnket = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="dtEgitimBasTarihAnket", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtEgitimBasTarihAnket {
            get {
                return this._dtEgitimBasTarihAnket;
            }
            set {
                this._dtEgitimBasTarihAnket = value;
            }
        }
        
        public E_EgitimTalepDegerlendirmeSureci_FormAnketVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketRDEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormAnketMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnketML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketMLEntity : MLEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitimAdiAnket;
        
        private Bimser.Framework.Domain.DataField<string> _TextBox1;
        
        private Bimser.Framework.Domain.DataField<string> _txDegerlendirmeAciklama;
        
        private Bimser.Framework.Domain.DataField<string> _tbxUnvanAnket;
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitmenAnket;
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitimYeriAnket;
        
        [ColumnOptionsAttribute(Name="tbxEgitimAdiAnket", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitimAdiAnket {
            get {
                return this._tbxEgitimAdiAnket;
            }
            set {
                this._tbxEgitimAdiAnket = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="TextBox1", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> TextBox1 {
            get {
                return this._TextBox1;
            }
            set {
                this._TextBox1 = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="txDegerlendirmeAciklama", Mandatory=false, Size=250)]
        public Bimser.Framework.Domain.DataField<string> txDegerlendirmeAciklama {
            get {
                return this._txDegerlendirmeAciklama;
            }
            set {
                this._txDegerlendirmeAciklama = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tbxUnvanAnket", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxUnvanAnket {
            get {
                return this._tbxUnvanAnket;
            }
            set {
                this._tbxUnvanAnket = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tbxEgitmenAnket", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitmenAnket {
            get {
                return this._tbxEgitmenAnket;
            }
            set {
                this._tbxEgitmenAnket = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tbxEgitimYeriAnket", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitimYeriAnket {
            get {
                return this._tbxEgitimYeriAnket;
            }
            set {
                this._tbxEgitimYeriAnket = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnketVR")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketVREntity : VersionEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketVREntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnketRDC")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketRDCEntity : RDCEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnketRDCML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketRDCMLEntity : RDCMLEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnketRD")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketRDEntity : RDEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketRDEntity, E_EgitimTalepDegerlendirmeSureci_FormAnketRDMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormAnketRDML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormAnketRDMLEntity : RDMLEntity<E_EgitimTalepDegerlendirmeSureci_FormAnketRDMLEntity> {
    }
}




