//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace EgitimTalepDegerlendirmeSureci.Entities {
    
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaEntity : FormEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtEgitimBasTarih;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> _dtEgitimBitTarih;
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _nbxKatilimciSayisi;
        
        private Bimser.Framework.Domain.DataField<string> _maskIban;
        
        private Bimser.Framework.Domain.DataField<decimal> _nbxEgitimBedel;
        
        private E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaVREntity _VersionEntity;
        
        private RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDMLEntity> _RD;
        
        private RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCMLEntity> _RDC;
        
        private MLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaMLEntity> _ML;
        
        private SLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLMLEntity> _SL;
        
        private GridEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity> _E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar;
        
        public E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaEntity() {
            this.ML = new MLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaMLEntity>();
            this.VersionEntity = new E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaVREntity();
            this.RD = new RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCMLEntity>();
            this.E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar = new GridEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity>();
            this.E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar.MLEntityEnabled = true;
            this.E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar.SLEntityEnabled = false;
            this.SL = new SLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLMLEntity>();
        }
        
        [ColumnOptionsAttribute(Name="dtEgitimBasTarih", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtEgitimBasTarih {
            get {
                return this._dtEgitimBasTarih;
            }
            set {
                this._dtEgitimBasTarih = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="dtEgitimBitTarih", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<System.DateTimeOffset>> dtEgitimBitTarih {
            get {
                return this._dtEgitimBitTarih;
            }
            set {
                this._dtEgitimBitTarih = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="nbxKatilimciSayisi", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> nbxKatilimciSayisi {
            get {
                return this._nbxKatilimciSayisi;
            }
            set {
                this._nbxKatilimciSayisi = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="maskIban", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> maskIban {
            get {
                return this._maskIban;
            }
            set {
                this._maskIban = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="nbxEgitimBedel", Mandatory=true)]
        public Bimser.Framework.Domain.DataField<decimal> nbxEgitimBedel {
            get {
                return this._nbxEgitimBedel;
            }
            set {
                this._nbxEgitimBedel = value;
            }
        }
        
        public E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
        
        public MLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaMLEntity> ML {
            get {
                return this._ML;
            }
            set {
                this._ML = value;
            }
        }
        
        public SLEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLMLEntity> SL {
            get {
                return this._SL;
            }
            set {
                this._SL = value;
            }
        }
        
        public GridEntityCollection<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity> E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar {
            get {
                return this._E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar;
            }
            set {
                this._E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaMLEntity : MLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _txEgitimTalepAciklama;
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitimYeri;
        
        private Bimser.Framework.Domain.DataField<string> _tbxEgitmen;
        
        [ColumnOptionsAttribute(Name="txEgitimTalepAciklama", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> txEgitimTalepAciklama {
            get {
                return this._txEgitimTalepAciklama;
            }
            set {
                this._txEgitimTalepAciklama = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tbxEgitimYeri", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitimYeri {
            get {
                return this._tbxEgitimYeri;
            }
            set {
                this._tbxEgitimYeri = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="tbxEgitmen", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> tbxEgitmen {
            get {
                return this._tbxEgitmen;
            }
            set {
                this._tbxEgitmen = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSL")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLEntity : SLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLMLEntity : SLMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaSLMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilar")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarEntity : GridEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarMLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity> {
        
        private Bimser.Framework.Domain.DataField<System.Nullable<decimal>> _USERID;
        
        public E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarEntity() {
        }
        
        [ColumnOptionsAttribute(Name="USERID", Mandatory=false)]
        public Bimser.Framework.Domain.DataField<System.Nullable<decimal>> USERID {
            get {
                return this._USERID;
            }
            set {
                this._USERID = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarMLEntity : GridMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarMLEntity> {
        
        private Bimser.Framework.Domain.DataField<string> _FULLNAME;
        
        private Bimser.Framework.Domain.DataField<string> _PROFESSION;
        
        [ColumnOptionsAttribute(Name="FULLNAME", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> FULLNAME {
            get {
                return this._FULLNAME;
            }
            set {
                this._FULLNAME = value;
            }
        }
        
        [ColumnOptionsAttribute(Name="PROFESSION", Mandatory=false, Size=50)]
        public Bimser.Framework.Domain.DataField<string> PROFESSION {
            get {
                return this._PROFESSION;
            }
            set {
                this._PROFESSION = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSL")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLEntity : GridSLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity : GridSLMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlama_dgKatilimcilarSLMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaVR")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaVREntity : VersionEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaVREntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDC")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCEntity : RDCEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCMLEntity : RDCMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRD")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDEntity : RDEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDEntity, E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDML")]
    public class E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDMLEntity : RDMLEntity<E_EgitimTalepDegerlendirmeSureci_FormEgitimPlanlamaRDMLEntity> {
    }
}




