//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Bimser.CSP.FormControls.Entities;
using Bimser.Framework.Attributes.Database;
using Bimser.Framework.Domain;
using Bimser.Framework.Domain.Entities;

namespace EgitimTalepDegerlendirmeSureci.Entities {
    
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_Archive")]
    public class E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveEntity : FormEntity<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveEntity> {
        
        private E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveVREntity _VersionEntity;
        
        private RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDMLEntity> _RD;
        
        private RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCMLEntity> _RDC;
        
        public E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveEntity() {
            this.VersionEntity = new E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveVREntity();
            this.RD = new RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDMLEntity>();
            this.RDC = new RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCMLEntity>();
        }
        
        public E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveVREntity VersionEntity {
            get {
                return this._VersionEntity;
            }
            set {
                this._VersionEntity = value;
            }
        }
        
        public RDEntityCollection<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDMLEntity> RD {
            get {
                return this._RD;
            }
            set {
                this._RD = value;
            }
        }
        
        public RDCEntityCollection<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCMLEntity> RDC {
            get {
                return this._RDC;
            }
            set {
                this._RDC = value;
            }
        }
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveVR")]
    public class E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveVREntity : VersionEntity<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveVREntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDC")]
    public class E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCEntity : RDCEntity<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCML")]
    public class E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCMLEntity : RDCMLEntity<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDCMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRD")]
    public class E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDEntity : RDEntity<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDEntity, E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDMLEntity> {
    }
    
    [TableOptions(TableName="E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDML")]
    public class E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDMLEntity : RDMLEntity<E_EgitimTalepDegerlendirmeSureci_FlowEgitimTalep_Process_ArchiveRDMLEntity> {
    }
}




